---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "32"
year: "2017"
contributor: 
- "Karsten Schuldt"
- "Rudolf Mumenthaler"
title: "Partizipation in Bibliotheken. Ein Experiment, eine Collage"
pdf: "master.pdf"
date: 2017-12-08 18:00
comments: false
sharing: true
footer: true

---