---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "32"
year: "2017"
contributor: 
- "Christian Gutknecht"
title: "Zur Situation von Open Access in der Schweiz: Interview mit Christian Gutknecht"
pdf: "master.pdf"
date: 2017-12-16 20:00
comments: false
sharing: true
footer: true

---