---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "32"
year: "2017"
contributor: 
- "Thomas Hartmann"
title: "Zwang zum Open Access-Publizieren? Der rechtliche Präzedenzfall ist schon da!"
pdf: "master.pdf"
date: 2017-11-29 20:00
comments: false
sharing: true
footer: true

---