---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "32"
year: "2017"
contributor: 
- "Thomas Hartmann"
title: "Zwang zum Open Access-Publizieren? Der rechtliche Präzedenzfall ist schon da!"
urn: "urn:nbn:de:kobv:11-110-18452/19845-8"
date: 2017-11-29 20:00
comments: false
sharing: true
footer: true

---