---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "32"
year: "2017"
contributor: 
- "Ulrich Herb"
title: "Ist Open Access an ein Ende gelangt? Ein Interview"
pdf: "master.pdf"
date: 2017-11-29 20:00
comments: false
sharing: true
footer: true

---