---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "32"
year: "2017"
contributor: 
- "Readktion LIBREAS"
title: "Editorial #32: Wirkung von Open Access"
pdf: "master.pdf"
date: 2017-11-29 20:00
comments: false
sharing: true
footer: true

---