---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "32"
year: "2017"
contributor: 
- "Readktion LIBREAS"
title: "Editorial #32: Wirkung von Open Access"
urn: "urn:nbn:de:kobv:11-110-18452/19841-4"
date: 2017-11-29 20:00
comments: false
sharing: true
footer: true

---