---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "32"
year: "2017"
contributor: 
- "Michael Kleineberg"
- "Ben Kaden"
title: "Open Humanities? ExpertInnenmeinungen über Open Access in den Geisteswissenschaften"
pdf: "master.pdf"
date: 2017-12-02 17:00
comments: false
sharing: true
footer: true

---