---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "32"
year: "2017"
contributor: 
- "Anita Czymborska"
title: "Open-Access-Ideologie und nachteilige Systemwirkungen. Einige Überlegungen"
pdf: "master.pdf"
date: 2017-12-16 20:00
comments: false
sharing: true
footer: true

---