---

layout: page
lang: "en"
journal: "LIBREAS. Library Ideas"
issue: "32"
year: "2017"
contributor: 
- "Bernhard Mittermaier"
title: "From the DEAL engine room &mdash; an interview with Bernhard Mittermaier"
pdf: "master.pdf"
date: 2017-12-01 23:00
comments: false
sharing: true
footer: true

---