---

layout: page
lang: "en"
journal: "LIBREAS. Library Ideas"
issue: "32"
year: "2017"
contributor: 
- "Bernhard Mittermaier"
title: "From the DEAL engine room &mdash; an interview with Bernhard Mittermaier"
urn: "urn:nbn:de:kobv:11-110-18452/19849-3"
date: 2017-12-01 23:00
comments: false
sharing: true
footer: true

---