---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "32"
year: "2017"
contributor: 
- "Redaktion LIBREAS"
title: "Das liest die LIBREAS, Nummer #1 (Sommer / Herbst 2017)"
urn: "urn:nbn:de:kobv:11-110-18452/19856-0"
date: 2017-11-29 20:00
comments: false
sharing: true
footer: true

---