---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "32"
year: "2017"
contributor: 
- "Bernhard Mittermaier"
title: "Aus dem DEAL-Maschinenraum &mdash; ein Gespräch mit Bernhard Mittermaier"
urn: "urn:nbn:de:kobv:11-110-18452/19848-6"
date: 2017-12-01 23:00
comments: false
sharing: true
footer: true

---