---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "32"
year: "2017"
contributor: 
- "Bernhard Mittermaier"
title: "Aus dem DEAL-Maschinenraum -- ein Gespräch mit Bernhard Mittermaier"
pdf: "master.pdf"
date: 2017-12-01 23:00
comments: false
sharing: true
footer: true

---