---
layout: page
journal: "LIBREAS. Library Ideas"
issue: "32"
year: "2017"
contributor: 
- "Steffi Grimm"
- "Dagmar Schobert"
title: "Open Access an der Universität verankern: Ein Praxisbericht aus dem Jahr 2017"
urn: "urn:nbn:de:kobv:11-110-18452/19843-6"
date: 2017-12-10 10:50
comments: false
sharing: true
footer: true
---