---
layout: page
journal: "LIBREAS. Library Ideas"
issue: "32"
year: "2017"
contributor: 
- "Nikolaus Hamann"
title: "Offenheit als demokratisches Prinzip"
urn: "urn:nbn:de:kobv:11-110-18452/19846-4"
date: 2017-12-10 10:50
comments: false
sharing: true
footer: true
---