---
layout: page
journal: "LIBREAS. Library Ideas"
issue: "32"
year: "2017"
contributor: 
- "Nikolaus Hamann"
title: "Offenheit als demokratisches Prinzip"
pdf: "master.pdf"
date: 2017-12-10 10:50
comments: false
sharing: true
footer: true
---